name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Lint with ruff
        run: python -m ruff check src tests

      - name: Check formatting with black
        run: python -m black --check src tests

      - name: Lint with flake8
        run: python -m flake8 src tests

      - name: Type-check with mypy
        run: python -m mypy src

      - name: Compile sources
        run: python -m compileall src

      - name: Run tests
        run: python -m pytest --cov=turingscreencli
